Sprint 1
podolskijspace/middle.messenger.praktikum.yandex pull request #4
Opened 2022-07-25 15:41 UTC by podolskijspace

2022-07-25 16:07 UTC, podlovchenko commented on package.json
> +    "build": "parcel build ./src/index.html"
Нет команды запуска сервера

2022-07-25 16:11 UTC, podlovchenko commented on src/scripts/pages/404.js
> +data = {}
Не вижу объявления этой переменной

2022-07-25 16:12 UTC, podlovchenko commented on src/scripts/pages/404.js
> +const root = document.querySelector('#root');
root нигде не используется

2022-07-25 16:13 UTC, podlovchenko commented on src/scripts/pages/500.js
> +export default errorPage
В проекте во многих файлах есть ошибка EOF
https://stackoverflow.com/questions/5813311/whats-the-significance-of-the-no-newline-at-end-of-file-log

2022-07-25 16:13 UTC, podlovchenko commented on src/styles/components/button.scss
> +    background: rgb(98, 233, 98);
Цвета лучше указывать через css переменные, так будет понятнее, что это за цвет при просмотре кода и проще редактировать цвета по всему проекту

2022-07-25 16:13 UTC, podlovchenko commented on src/styles/components/chatSM.scss
> +    #{$self}.active & {
Для чего self?

2022-07-26 12:42 UTC, podolskijspace commented on package.json
> +    "@parcel/transformer-sass": "^2.6.2",
А при установке можно как-то написать, чтобы сразу фиксированную версию он задал?

2022-07-26 12:46 UTC, podolskijspace commented on src/scripts/pages/404.js
> +export default notFoundPage
Очень сложно читать на английском, но я попробую осилить эту статью, спасибо

2022-07-26 13:05 UTC, podolskijspace commented on src/styles/components/chatSM.scss
> +    #{$self}.active & {
Помогает обращаться через модификаторы и вспомогательные классы. Например, у нас есть элемент, у него есть блок, а у элемента есть модификатор, вместо. У нас что-то около такого кода:

`
.elem {
  &__block{
    
  }
}
`

Далее, чтобы добавить модификатор, мы можем сделать

`
&.modificator &__block{`
Или что-то подобное, но я заменяю elem на self и изнутри блока через модификатор обращаюсь, таким образом у меня рядом блок и его разные стили, в зависимости от модификаторов элементов

2022-07-26 16:16 UTC, podlovchenko commented on src/styles/components/chatSM.scss
> +    #{$self}.active & {
Выглядит как излишнее усложнение, можно же просто & оставить

2022-07-26 16:18 UTC, podlovchenko commented on package.json
> +    "@parcel/transformer-sass": "^2.6.2",
Устанавливать с ключом --save-exact

2022-07-26 16:23 UTC, podlovchenko requested changes
Привет
npm run build падает
<img width="918" alt="Снимок экрана 2022-07-26 в 19 19 23" src="https://user-images.githubusercontent.com/22602747/181059032-0e3a3d45-36b2-44be-91f8-1041959f787b.png">
На нетлифае
<img width="1639" alt="Снимок экрана 2022-07-26 в 19 20 16" src="https://user-images.githubusercontent.com/22602747/181059064-2abb8d85-d5d6-40de-889b-a305995faf78.png">

2022-07-26 16:23 UTC, podlovchenko commented on src/styles/components/button.scss
> +    background: #{$mainColor};
Можно просто
```suggestion
    background: $mainColor;
```

2022-07-26 16:23 UTC, podlovchenko commented on src/styles/components/button.scss
> +    background: #{$mainColor};
Цвета лучше вынести в одно место и использовать по всему проекту

2022-07-27 08:57 UTC, podolskijspace commented on src/styles/components/button.scss
> +    background: #{$mainColor};
Всё это исправил)

2022-07-27 08:58 UTC, podolskijspace commented on src/styles/components/button.scss
> +    background: #{$mainColor};
Я не знаю, правильно это или нет, я не стал заливать эту ветку, в ветку deploy, я просто настроил деплой на sprint__1

2022-07-27 17:45 UTC, podlovchenko commented
Привет, сейчас приложение не отдает другие страницы
Нужно добавить в server.js
```
app.get('/*', (req, res) => {
  res.sendFile(path.join(__dirname, 'dist/index.html'));
});
```
Нет ссылки на фигму

2022-07-28 07:38 UTC, podolskijspace commented
Добавил ссылку на фигму, я использовал стандартные макеты, по ним примерно верстал, не вдаваясь в детали. Сервер поправил, теперь корректно работает, спасибо за подсказку

2022-07-28 09:21 UTC, podlovchenko commented
Работу принимаю, но сильное расхождение по макетам, попробуй к следующему спринту привести в соответствие)

2022-07-28 09:43 UTC, podolskijspace commented
Спасибо, я приведу к макетам, либо сделать свои)

2022-07-28 11:13 UTC, merged